### ISSUE TITLE
New URL and versions (please read)

### ISSUE THREAD

**Issue by cidrblock** [cidrblock/td4a#21]
td4a has a new home and URL, I also updated to python 3 and the dependent version packages, pushed to pypi and docker hub.

Please let me know if you see or find any issues here.

Thanks- Brad

https://td4a.codethenetwork.com

**Comment by Nudin** [comment]
HI, seems like some of the dependencies are broken again. To make it work, I needed to pin the following dependency versions:
```
jinja2==3.0
werkzeug==2.0.3
itsdangerous==2.0.1
```

**Comment by Nudin** [comment]
And here are the corresponding tracebacks:

```
Traceback (most recent call last):
  File "/home/michi/bin/td4a_venv/bin/td4a-server", line 2, in <module>
    from td4a import app
  File "/home/michi/bin/td4a_venv/lib/python3.10/site-packages/td4a/__init__.py", line 1, in <module>
    from flask import Flask, request, jsonify
  File "/home/michi/bin/td4a_venv/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/michi/bin/td4a_venv/lib/python3.10/site-packages/jinja2/__init__.py)
```


```
Traceback (most recent call last):
  File "/home/michi/bin/td4a_venv/bin/td4a-server", line 2, in <module>
    from td4a import app
  File "/home/michi/bin/td4a_venv/lib/python3.10/site-packages/td4a/__init__.py", line 1, in <module>
    from flask import Flask, request, jsonify
  File "/home/michi/bin/td4a_venv/lib/python3.10/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/michi/bin/td4a_venv/lib/python3.10/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/home/michi/bin/td4a_venv/lib/python3.10/site-packages/itsdangerous/__init__.py)
```

```
Traceback (most recent call last):
  File "/home/michi/bin/td4a_venv/bin/td4a-server", line 2, in <module>
    from td4a import app
  File "/home/michi/bin/td4a_venv/lib/python3.10/site-packages/td4a/__init__.py", line 1, in <module>
    from flask import Flask, request, jsonify
  File "/home/michi/bin/td4a_venv/lib/python3.10/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/home/michi/bin/td4a_venv/lib/python3.10/site-packages/flask/app.py", line 32, in <module>
    from werkzeug.wrappers import BaseResponse
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' (/home/michi/bin/td4a_venv/lib/python3.10/site-packages/werkzeug/wrappers/__init__.py)
```

**Comment by jabelk** [comment]
@cidrblock thanks for all your work on this project! I use it to teach Ansible / YAML / J2, since it is easy for folks to get started with a public URL and not set up local system yet.

I noticed the public page is down:
https://td4a.codethenetwork.com/

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<script/>
<script/>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist.</Message>
</Error>
```

Any chance it will be able to be fixed soonish?

**Comment by tracure1337** [comment]
This is a  very helpful tool. Any chance it will be made current again?

**Comment by tigattack** [comment]
I've forked this, bumped dependencies, and made a release at https://github.com/tigattack/td4a. I don't plan on hosting a public version but it's super easy to get running, just as cidrblock's version is :)

Working great for me, feel free to throw an issue my way if anything comes up.
